# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

deploy:
  - provider: GitHub
    artifact: '.*\.(tar\.gz|zip)'
    force_update: true
    auth_token: '$GH_TOKEN'

before_deploy:
  cmd: |
    Rscript -e "install.packages('drat', repos = 'https://cloud.r-project.org')"
    git clone --depth 1 https://$GH_TOKEN@github.com/inbo/drat.git ../drat --branch=gh-pages
    git config --global user.email "thierry_onkelinx@inbo.be"
    git config --global user.name "ThierryO"
    Rscript -e "drat::insertPackage(list.files(pattern = 'tar.gz'), '../drat')"
    Rscript -e "drat::insertPackage(list.files(pattern = 'zip'), '../drat')"
    cd ../drat
    git commit --all -m "INBOmd from appveyor"
    git push origin
