# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

  - path: 'DESCRIPTION'
    name: pkgdown

  - path: 'LICENSE'
    name: pkgdown

  - path: 'man'
    name: pkgdown

  - path: '*.md'
    name: pkgdown

environment:
  access_token:
    secure: yysQI1zM7yUTewFfHSAPixDMQPH2/Zik3AxI/WSOSM3eHOttl5ZzXbxrb6PjUn5y

deploy:
  - provider: GitHub
    artifact: '.*\.(tar\.gz|zip)'
    force_update: true
    auth_token:
      secure: yysQI1zM7yUTewFfHSAPixDMQPH2/Zik3AxI/WSOSM3eHOttl5ZzXbxrb6PjUn5y

before_deploy:
  - Rscript -e "install.packages(c('drat', 'devtools'), repos = 'https://cloud.r-project.org')"
  - Rscript -e "devtools::instal_github('hadley/pkgdown')"
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "bmk@inbo.be"
  - git config --global user.name "INBO CI"
  - git clone --depth 1 https://github.com/inbo/drat.git drat --branch=gh-pages
  - Rscript -e "drat::insertPackage(list.files(pattern = 'tar.gz'), 'drat')"
  - Rscript -e "drat::insertPackage(list.files(pattern = 'zip'), 'drat')"
  - Rscript -e "pkgdown::build_site(path = 'drat/docs/inbomd')"
  - cd drat
  - git add --all
  - git commit -m "INBOmd from appveyor"
  - git push origin
